const token =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGlfZXNjb2xhLWZ1dGVib2wiLCJhdWQiOiJkaXZlcnNvc19hcHAiLCJpYXQiOjE2MjY2NDIzMDIsIm5iZiI6MTYyNjY0MjMxMiwiZXhwIjoxNjI2NjQ1OTAyfQ.nIu9YuSNQ4jMnoBhqodm-m2OrnrEoLah-7Ql36x8UG0";

export default token;
